### ISSUE TITLE
Define all blocks using translation message

### ISSUE THREAD

**Issue by kristiank** [GIRA/UziScript#13]
Although some blocks don't currently include any text (e.g. pins, numbers and variables) I think it would be wise to define them using the `initBlock` function and a translation text. One thing this would allow from my perspective is age-specific translations. For very young users it makes sense to add the word "number" on the number block.

**Comment by RichoM** [comment]
Yes, I agree.

**Comment by kristiank** [comment]
Here is a list of the blocks that are still not defined using the `initBlock` function:
  * [ ] comment blocks
  * [ ] pin names
  * [x] number (was added in #21)
  * [ ] procedure call blocks
  * [ ] function evaluation blocks
  * [ ] return block
  * [ ] return with value block

**Comment by kristiank** [comment]
The comment blocks are actually already translatable (e.g. `i18n.translate("This is a comment")`), so I think the issue here could be closed after merging #22. But what is the status of the comment blocks, are you planning to use them?

**Comment by RichoM** [comment]
> But what is the status of the comment blocks, are you planning to use them?

Not sure. The problem with the comment blocks is that they only allow to put blocks in some specific places while the language grammar is much more flexible. Also, Blockly has its own comment mechanism so maybe I'll use that. But I haven't decided yet.
