### ISSUE TITLE
Auto select and remember localization language depending on browsers settings

### ISSUE THREAD

**Issue by kristiank** [GIRA/UziScript#14]
Currently Spanish seems to be the language selected by default. It would be nice if PhysicalBITS would react to the browsers' language settings.

Also, a cookie could be used to remember last chosen language.

**Comment by kristiank** [comment]
Found the code that sets Spanish per default here [web/ide/ide.js#L587](https://github.com/GIRA/UziScript/blob/1e670cc661be8442a522d07b5c6b99fea4ca4819/web/ide/ide.js#L587)

I'll have a look at how to change this some time soonish.

**Comment by RichoM** [comment]
Yes, absolutely. I hardcoded spanish as a temporary solution for my needs at the time but it should use the browser settings. 

To preserve the user settings I'm currently using localStorage. Maybe we can add the user language in there as well.

**Comment by kristiank** [comment]
> To preserve the user settings I'm currently using localStorage. Maybe we can add the user language in there as well.

Yes, absolutely. And also the all-caps-mode setting could be saved. But how should it be structured? Could I put them to the UI state object like this:

```javascript
  function getUIState() {
    return {
      settings: {
        interactive: $("#interactive-checkbox").get(0).checked,
        locale: i18n.currentLocale(),                     // <-- this one
        all-caps: $("#all-caps-checkbox").get(0).checked, // <-- and this
      },
      layout: layout.toConfig(),
      blockly: UziBlock.getDataForStorage(),
    };
  }
```

**Comment by kristiank** [comment]
I created a pull request for a first draft on autodetection functionality in #19.

**Comment by RichoM** [comment]
> But how should it be structured? Could I put them to the UI state object like this:

Yes, exactly.

**Comment by kristiank** [comment]
This seems to be working now and could be closed. What do you think? I'll let you close this.

**Comment by RichoM** [comment]
Ok, closed!
